# Konfigurasi Docker Compose untuk pembangunan
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
    volumes:
      - .:/var/www/html
    depends_on:
      - database
      - redis

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ictserve
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data:
