module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-tailwindcss',
  ],
  plugins: [
    'stylelint-order',
    'stylelint-declaration-block-no-ignored-properties',
  ],
  rules: {
    'block-no-empty': true,
    'no-descending-specificity': null,
    'order/properties-order': [
      [
        'position',
        'z-index',
        'top',
        'right',
        'bottom',
        'left',
        'display',
        'flex',
        'flex-direction',
        'flex-wrap',
        'flex-flow',
        'align-items',
        'align-content',
        'justify-content',
        'order',
        'float',
        'clear',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'margin',
        'padding',
        'font',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'letter-spacing',
        'color',
        'background',
        'background-color',
        'background-image',
        'background-size',
        'background-position',
        'background-repeat',
        'border',
        'border-radius',
        'box-shadow',
        'opacity',
        'overflow',
        'visibility',
        'transition',
        'animation',
      ],
      { unspecified: 'bottomAlphabetical' },
    ],
  'plugin/declaration-block-no-ignored-properties': true,
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'tailwind',
          'apply',
          'variants',
          'responsive',
          'screen',
          'layer',
          'theme',
          'import',
        ],
      },
    ],
    'property-no-vendor-prefix': true,
    'value-no-vendor-prefix': true,
  // Allow kebab-case, BEM, utility, and design system class naming
    'selector-class-pattern': [
      // Regex: kebab-case, BEM (block__element--modifier), utility (bg-primary-600, radius-m, etc)
  // Allows: .ds-card, .ds-card__body, .ds-btn--primary, .text-primary, .bg-primary-600, .radius-m, .pill-success, .skip-link, etc
      '^([a-z0-9]+([_-]{1,2}[a-z0-9]+)*)+$',
      {
        "message": "Selector should be kebab-case, BEM, or utility class (lowercase, hyphens, underscores, numbers only)",
      },
    ],
  },
}
